### ISSUE TITLE
后端接口字段是变化的该咋整

### ISSUE THREAD

**Issue by zmm2tysu** [fluttercandies/JsonToDart#12]
eg: 
`正常情况：{code: 1, message: '', data: {id: 1, name: 'flutter'}}`
`非正常情况：{code: -99, message: '', data: {}}`
我理解的这两种情况在代码中
![image](https://user-images.githubusercontent.com/20849786/126997059-241d883c-e586-435f-ba3d-ed484fd17a98.png)

都会直接return，然后就会报`Null check operator used on a null value`
由于我一开始接的yapi，返回结果都是正常的。。所有全部用的required，就类似下面这种

![image](https://user-images.githubusercontent.com/20849786/126997406-a81d8f5b-8bfa-40b7-b866-14850091272a.png)

现在项目把所有yapi接口都接完了....结果对接真实接口出了这么个鬼问题，想咨询下有没有成本相对来说小点的修改方案

**Comment by zmtzawqlp** [comment]
自己重写下convert方法

**Comment by zmtzawqlp** [comment]
后端字段变化。应该打他们一顿

**Comment by zmtzawqlp** [comment]
https://github.com/fluttercandies/ff_annotation_route_library/blob/master/lib/src/helper.dart

**Comment by zmm2tysu** [comment]
咋重写啊？ 是自己获取到T的类型然后new一个带默认值的对象么？  我已经改完了170多个文件=。=

**Comment by zmtzawqlp** [comment]
那你为啥不改成 可空类型呢

**Comment by zmm2tysu** [comment]
我昨天改了170多个文件 弄好了...只是你说的convert重写这里没有思路解决这种问题

**Comment by zmtzawqlp** [comment]
重写convert，如果为null，返回你泛型T的默认值呗

**Comment by zmm2tysu** [comment]
T是对象的默认值咋给？ 可以直接  new T么

**Comment by zmtzawqlp** [comment]
你自己哪些类 可能出现这个问题，不清楚吗。每个class 来一个默认。  if(T is A())

**Comment by zmm2tysu** [comment]
...这样看来还是把data弄成可空吧  不然每个类都得设置默认值.
