### ISSUE TITLE
web方式如何使用？

### ISSUE THREAD

**Issue by disburden** [fluttercandies/JsonToDart#21]
https://fluttercandies.github.io/JsonToDart/
https://zmtzawqlp.gitee.io/jsontodart/
上面两个网址我打开之后都是一个静态的页面，怎么点击都没反应
我平时用的是linux，只能用web的方式

**Comment by zmtzawqlp** [comment]
比较慢，耐心等等

**Comment by zmtzawqlp** [comment]
<img width="864" alt="截屏2022-06-27 11 54 50" src="https://user-images.githubusercontent.com/16477333/175856899-04cf01aa-b7f6-424f-80dd-22e3f6adf70e.png">
<img width="770" alt="截屏2022-06-27 11 54 58" src="https://user-images.githubusercontent.com/16477333/175856909-0f2df87d-5bd1-4a2d-8622-c8c32b57db68.png">

**Comment by zmtzawqlp** [comment]
实际上。你可以clone 下拉。打一个linux的安装包

**Comment by zmtzawqlp** [comment]
这个就是个flutter 项目。你打linux 就好了呢

**Comment by disburden** [comment]
哦哦，我试试
