### ISSUE TITLE
类型/名字超出长度会重叠

### ISSUE THREAD

**Issue by 309791679** [fluttercandies/JsonToDart#25]
![捕获](https://user-images.githubusercontent.com/26238458/201450805-0ffa8508-d039-40a5-b36c-8fd5e94d46f5.PNG)

名称：rotationPicture，重叠后因为列表有自适应拉长也没有用，只能最大化，建议将列改为可调整大小的列表

**Comment by zmtzawqlp** [comment]
这个不好做，而且影响也不大。
