### ISSUE TITLE
包含重复类

### ISSUE THREAD

**Issue by Lazydd** [fluttercandies/JsonToDart#32]
```
{
  "suggest_words": {
    "suggest_words": [
      {
        "words": ""
      }
    ]
  }
}
```

```suggest_words```
这种格式不支持，包含重复类

**Comment by zmtzawqlp** [comment]
会有提示，然后你可以自己修改下
<img width="1094" alt="截屏2024-11-11 15 08 33" src="https://github.com/user-attachments/assets/1a59224f-216d-43ee-8dc7-9ac5f26f04c0">

**Comment by Lazydd** [comment]
> 会有提示，然后你可以自己修改下 <img alt="截屏2024-11-11 15 08 33" width="1094" src="https://private-user-images.githubusercontent.com/16477333/384820705-1a59224f-216d-43ee-8dc7-9ac5f26f04c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTU0MzIsIm5iZiI6MTczMTM5NTEzMiwicGF0aCI6Ii8xNjQ3NzMzMy8zODQ4MjA3MDUtMWE1OTIyNGYtMjE2ZC00M2VlLThkYzctOWFjNWYyNmYwNGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA3MDUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhOTZlMTAyYmU1Yjg3YTI0NTFhMWY0NjkxMWFhMDBmYTY2YTNiMDY2M2YyM2JmZTBlOTA2OTY4ZTYxODg2ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rSufHshEYFHf-uNhhLjHHSA3wNdKU4nbaY4oZyptBgM">

https://javiercbk.github.io/json_to_dart/

**Comment by zmtzawqlp** [comment]
> > 会有提示，然后你可以自己修改下 <img alt="截屏2024-11-11 15 08 33" width="1094" src="https://private-user-images.githubusercontent.com/16477333/384820705-1a59224f-216d-43ee-8dc7-9ac5f26f04c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzOTU0MzIsIm5iZiI6MTczMTM5NTEzMiwicGF0aCI6Ii8xNjQ3NzMzMy8zODQ4MjA3MDUtMWE1OTIyNGYtMjE2ZC00M2VlLThkYzctOWFjNWYyNmYwNGMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDA3MDUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhOTZlMTAyYmU1Yjg3YTI0NTFhMWY0NjkxMWFhMDBmYTY2YTNiMDY2M2YyM2JmZTBlOTA2OTY4ZTYxODg2ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rSufHshEYFHf-uNhhLjHHSA3wNdKU4nbaY4oZyptBgM">
> 
> https://javiercbk.github.io/json_to_dart/

你就算生成了。也会报错啊。。一样的class 名字
