### ISSUE TITLE
修改root类型时 程序异常退出

### ISSUE THREAD

**Issue by hqwlkj** [fluttercandies/JsonToDart#4]
![image](https://user-images.githubusercontent.com/12181423/68909632-f1640780-0789-11ea-8487-56795d7e6952.png)

**Comment by zmtzawqlp** [comment]
mac吗？

**Comment by hqwlkj** [comment]
@zmtzawqlp   是的

**Comment by zmtzawqlp** [comment]
试试最新上传的mac-go-flutter.zip

**Comment by hqwlkj** [comment]
好的
