### ISSUE TITLE
生成的实体类异常

### ISSUE THREAD

**Issue by lixianyan** [fluttercandies/JsonToDart#8]
{"data":{"makes":{"data":[{"value":123,"title":"AUDI"},{"value":124,"title":"AUSTIN MORRIS"},{"value":125,"title":"BAW"},{"value":126,"title":"BENTLEY"},{"value":127,"title":"BISON"},{"value":128,"title":"BMW"},{"value":129,"title":"CAM"},{"value":130,"title":"CHANGAN"},{"value":131,"title":"CHERY"},{"value":132,"title":"CHEVROLET"},{"value":133,"title":"CITROEN"},{"value":134,"title":"DAIHATSU"},{"value":135,"title":"DONG FENG"},{"value":136,"title":"FARID"},{"value":138,"title":"FIAT"},{"value":139,"title":"FORD"},{"value":140,"title":"FOTON"},{"value":137,"title":"Ferrari"},{"value":141,"title":"GREAT WALL"},{"value":142,"title":"HAVAL"},{"value":143,"title":"HONDA"},{"value":144,"title":"HUANGHAI"},{"value":145,"title":"HYUNDAI"},{"value":146,"title":"INFINITI"},{"value":147,"title":"INOKOM"},{"value":148,"title":"ISUZU"},{"value":149,"title":"JAGUAR"},{"value":150,"title":"JEEP"},{"value":151,"title":"JOYLONG"},{"value":152,"title":"KIA"},{"value":153,"title":"KING LONG XIAMEN"},{"value":154,"title":"LAND ROVER"},{"value":155,"title":"LEXUS"},{"value":156,"title":"MAHINDRA"},{"value":157,"title":"MASERATI"},{"value":158,"title":"MAZDA"},{"value":159,"title":"MERCEDES-BENZ"},{"value":160,"title":"MG ROVER"},{"value":161,"title":"MINI"},{"value":162,"title":"MITSUBISHI"},{"value":163,"title":"MITSUOKA"},{"value":164,"title":"NAZA"},{"value":165,"title":"NISSAN"},{"value":166,"title":"PERODUA"},{"value":167,"title":"PEUGEOT"},{"value":168,"title":"PORSCHE"},{"value":169,"title":"PROTON"},{"value":170,"title":"RENAULT"},{"value":171,"title":"SAAB"},{"value":172,"title":"SCODA"},{"value":173,"title":"SHENYANG BRILLIANCE JINBEI"},{"value":174,"title":"SKODA"},{"value":175,"title":"SMART"},{"value":176,"title":"SSANGYONG"},{"value":177,"title":"SUBARU"},{"value":178,"title":"SUZUKI"},{"value":179,"title":"TOYOTA"},{"value":180,"title":"VOLKSWAGEN"},{"value":181,"title":"VOLVO"},{"value":182,"title":"WESTSTAR MAXUS"},{"value":183,"title":"XIAMEN"}]},"locations":[{"title":"Glenmarie","value":1},{"title":"Cheras","value":2},{"title":"Puchong","value":3},{"title":"Johor Bahru (Tebrau)","value":4},{"title":"USJ","value":6},{"title":"Kuantan","value":7},{"title":"Melaka","value":8},{"title":"Seremban","value":9},{"title":"Ipoh","value":10},{"title":"Penang","value":11},{"title":"Alor Setar","value":12},{"title":"Klang","value":13},{"title":"Kajang","value":14},{"title":"Mobile","value":15},{"title":"vBranch SD","value":16},{"title":"vBranch Proton","value":17},{"title":"Batu Pahat","value":18},{"title":"Johor Bahru (Eco Business Park)","value":19},{"title":"Taman Megah","value":20},{"title":"Johor Bahru (Batu Pahat)","value":21},{"title":"Setia Alam","value":22}],"status":{"inspections":{"data":[{"value":57,"title":"Draft","scope":"inspections","subscope":"general"},{"value":58,"title":"Completed","scope":"inspections","subscope":"general"},{"value":297,"title":"Verified","scope":"inspections","subscope":"general"},{"value":298,"title":"Pending","scope":"inspections","subscope":"general"},{"value":299,"title":"Rejected","scope":"inspections","subscope":"general"},{"value":306,"title":"Car In","scope":"inspections","subscope":"pre-handover"},{"value":307,"title":"Done","scope":"inspections","subscope":"pre-handover"},{"value":308,"title":"Review","scope":"inspections","subscope":"pre-handover"},{"value":309,"title":"Approve","scope":"inspections","subscope":"pre-handover"},{"value":312,"title":"Reject","scope":"inspections","subscope":"pre-handover"}]}},"vehicle_condition":[{"title":"Excellent","value":"excellent"},{"title":"Good","value":"good"},{"title":"Fair","value":"fair"},{"title":"Poor","value":"poor"}]},"success":{"message":"Retrieve list of dropdown successfully!"}}

这种结构的json 生的实体是这样的
![image](https://user-images.githubusercontent.com/9101587/112840066-7c207a80-90d1-11eb-9e00-d6dc2d76e523.png)

**Comment by zmtzawqlp** [comment]
为啥不自己改类名
